name: "build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: sudo apt update && sudo apt install -y cabal-install
    - run: nix-shell --command "cabal update"
    - run: nix-shell --command "cabal build"
